version: "3.8"

services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND=http://localhost:3002
    ports:
      - "3000:3000"
    user: root
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
